### ISSUE TITLE
ElasticBeanstalk resources are being detected / deleted, but we are unable to whitelist resources on our cleanup site

### ISSUE THREAD

**Issue by dikuesan1** [servian/aws-auto-cleanup#115]
**Describe the bug**
After running the cleanup, ElasticBeanstalk resources can not be whitelisted on our exemption site. 

**To Reproduce**

1. Go to 'ElasticBeanstalk console'
2. Click on ' Create a new environment'
3. Create new environment and application
4. Run the cleanup in dry run mode
5. Check Cleanup site to whitelist an ElasticBeanstalk resource

**Expected behavior**
The expected behavior is for a window to pop up once you click the "+", then you are expected to input the owner and reason why you would like to whitelist the resource. I enabled EC2 resources during this testing and was able to whitelist one of the instance after running in dry run mode but when selecting the "+" beside an ElasticBeanstalk resource, the "+" functionality is unresponsive.

**Screenshots**

<img width="911" alt="ElasticBeanstalk detection after cleanup" src="https://user-images.githubusercontent.com/73569214/176172594-65de57e8-61c3-4bee-9e5d-2b7340c3fe8a.PNG">

**AWS (please complete the following information):**

- Region: [us-east-1 & us-east-2]

**Additional context**

In the screenshot, you will see the yellow "+" button in the Exception List column that I am referring to. For some reason the functionality is unresponsive. Any of resource tested, this functionality works. On ElasticBeanstalk resources behave in an unresponsive manner after detection. 

Haven't been able to get this working on my end.

**Comment by mlevit** [comment]
Hey @dikuesan1. Just did a little digging and I think I know what the issue is. The service is the log is `Elastic Beanstalk` but the service in my app settings is `elasticbeanstalk` which is really based on the way the servie is named in Boto3.

The problem is, when you press that button, the serivce name, resource, and ID are sent to a JS function called `createAllowlistEntryFromExecutionLog` where the service name has its spaces (` `) replaced by underscores (`_`) and is lowercased to match the service name in the app settings. But as you can see, they won't match because `elastic_beanstalk` != `elasticbeanstalk`.

So i'll have to update the service name in my app settings to have an underscore seperator. This will however have an impact on existing allowlists. I'll make the change and ask you to test/validate if that's OK.

**Comment by mlevit** [comment]
@dikuesan1 can you pull this branch and test it? https://github.com/servian/aws-auto-cleanup/tree/115-elasticbeanstalk-resources-are-being-detected-deleted-but-we-are-unable-to-whitelist-resources-on-our-cleanup-site

The app settings have changed so this will impact any allowlists.
